### ISSUE TITLE
triangulte breaks rust-analyzer

### ISSUE THREAD

**Issue by Hexorg** [colinjneville/triangulate#3] opened 2024-09-26 00:51 UTC
Rust analyzer fails with recursion limits:
```
error[E0275]: overflow evaluating the requirement `<OldIndex as Mappable<_>>::Output<_>: Mappable<_>`
   --> /home/hexorg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/triangulate-0.2.0/src/inputs/polygon_list.rs:367:9
    |
367 |         IndexWithIter::new(self.0.iter_indices())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`triangulate`)
note: required by a bound in `IndexWithIter::<'i, Iter, OldIndex, New, Old>::new`
   --> /home/hexorg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/triangulate-0.2.0/src/inputs/polygon_list.rs:316:65
    |
316 |       OldIndex::Output<New>: VertexIndex + crate::Mappable<New, Output<Old> = OldIndex> {
    |                                                                 ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `IndexWithIter::<'i, Iter, OldIndex, New, Old>::new`
317 |     pub(crate) fn new(iter: Iter) -> Self {
    |                   --- required by a bound in this associated function

```

**Comment by colinjneville** [comment] 2024-11-18 04:03
Duplicate of #4

**Closed as not planned by colinjneville** 2024-11-18 04:03 UTC
